### ISSUE TITLE
Using Easy Piglins or Villagers together with Catalogue will make so no entites/particles render when loading into the world

### ISSUE THREAD

**Issue by Sakatsuky** [henkelmax/easy-piglins#12]
**Bug description**
When using Catalogue mod together with Easy Piglins and/or Easy Villagers, changing a config from any mod(not only Easy P/V) will make so when you load into the world all entities/particles will not render.

This also happened with Alex Mobs, but was fixed, the problem is describled with more details in [MrCrayfish/Catalogue/#44](https://github.com/MrCrayfish/Catalogue/#44)

**Steps to reproduce the issue**
Use Easy Piglins or Easy Villagers together with the Catalogue mod.

**Expected behavior**
Changing mod configs and the entities/particles keep rendering.

**Versions**
- Minecraft version: 1.19.2
- Mod loader: Forge
- Mod loader version: 43.3.5
- Mod version: 1.0.0

**Comment by henkelmax** [comment]
Does this still happen with later versions of the mod?

**Comment by BritneyMc0206** [comment]
In case Sakatsuky doesn't reply due to it being so long since they posted this, give me a day and I'll let you know if later versions have this issue.

**Comment by BritneyMc0206** [comment]
I took a look at version 1.19.3 with no other mods besides the mentioned 3 and mca reborn (just to find a village easily), no problems with either entities nor particles. I also checked in version 1.20.1 with some other mods and saw no issues there. I think, unless Sakatsuky did something else or had another mod that was interfering, then versions after 1.19.2 are free from this issue, or atleast the latest of those versions.

**Comment by henkelmax** [comment]
Did you also test the 1.19.2 version of the mod? @Sakatsuky was using version 1.0.0 which is very old.

**Comment by BritneyMc0206** [comment]
Seems to be the same. Either something got fixed since this post or something else caused the issue.

**Comment by henkelmax** [comment]
Alright then, thank you for the help :)
