### ISSUE TITLE
Catalogue menu breaks when using Easy Piglins

### ISSUE THREAD

**Issue by TrueVoidwalkerx** [henkelmax/easy-piglins#14]
### Bug description

When Easy Piglins is installed with Catalogue, a popular mod that replaced the Mods menu on Forge, and Easy Piglins is being shown on the list, the entire menu breaks.
It seems to fix itself if you go into a config menu or you select the Update Check (the button with the green diamond), so most likely it's some issue that happens on startup and isn't properly addressed until it gets updated later

This also appears to happen with the Easy Villagers mod (of which I also made a report for this issue on)

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.5

### Mod loader and version

NeoForge 47.1.105

### Steps to reproduce

1.) Install Catalogue
2.) Run the game (it should look normal)
3.) Install Easy Piglins
4.) Menu broken

### Expected behavior

Without Easy Piglins
![image](https://github.com/henkelmax/easy-piglins/assets/78991053/edfa16cf-65f6-475a-829d-3ee868238147)

With Easy Piglins:
![image](https://github.com/henkelmax/easy-piglins/assets/78991053/cd361219-0237-45ff-bcd3-d63cd5f80183)
(the issue is even more apparent when you're using Easy Piglins in a bigger modpack)

### Log files

https://gist.github.com/GamingEinstein/e08a5b42f537636cbada39943de06582

**Comment by henkelmax** [comment]
That seems to be an issue with Catalogue then. Please report it to their issue tracker.

**Comment by henkelmax** [comment]
Closed due to inactivity.
