### ISSUE TITLE
[1.17.1] Server crashes when Easy Piglins is present on the server.

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/easy-piglins#3]
**Bug description**
When the mod is loaded on a server the server crashes.

**Steps to reproduce the issue**
1. Install mod on a server.
2. Try starting the server.
3. Server crashes.
4. See crash-report below.

**Expected behavior**
No crashes and the server starts as normal.

**Log files / Crash report**
https://gist.github.com/Gbergz/f243ee61e45cdebbb1835b1dce616be6

**Versions**
- Minecraft version: 1.17.1
- Forge version: 37.0.25
- Mod version: 1.0.1 | This one: https://www.curseforge.com/minecraft/mc-mods/easy-piglins/files/3401971

**Other mods**
No other mods are active, this is on a clean server. ONLY Easy Piglins is present.

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.
