### ISSUE TITLE
This is a Korean translation.

### ISSUE THREAD

**Issue by hayanggom** [henkelmax/easy-piglins#4]
This is a Korean translation.

je:69
Name(transliteration):한국어 (Hangugeo)
Language:Korean
In-hame:ko_kr

[ko_kr.json.txt](https://github.com/henkelmax/easy-piglins/files/8489666/ko_kr.json.txt)

{
  "block.easy_piglins.barterer": "물물교환",
  "itemGroup.easy_piglins": "쉬운 피글린",
  "gui.easy_piglins.input_items": "아이템 입력",
  "gui.easy_piglins.output_items": "아이템 출력",
  "message.easy_piglins.cant_pick_up": "공격적이거나 바쁜 피글린은 잡을 수 없습니다."
}

**Comment by henkelmax** [comment]
Thank you!
